<template>
  <transition name="v">
    <div v-show="isShow" class="loading">
      <div class="loadingio-spinner-spin-txhf5g2i8fm">
        <div class="ldio-c6v5n6da6eo">
          <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
        </div>
      </div>
      <span>{{ msg }}</span>
    </div>
  </transition>
</template>

<script lang="tsx">
import { defineComponent, onMounted, getCurrentInstance, ref } from 'vue'

export default defineComponent({
  name: 'Loading',
  props: {
    msg: {
      type: String
    },
  },
  setup(props, context) {
    const isShow = ref(false)
    return {
      isShow
    }
  },
  methods: {
    show() {
      this.isShow = true
      this.$emit('show')
    },
    hide() {
      this.isShow = false
    },
  },
  mounted() {
    console.log('挂载')
  },
  unmounted() {
    console.log('卸载')
  }

})
</script>

<style lang="stylus">
.loading
  position fixed
  top 0
  left 0
  right 0
  bottom 0
  display flex
  flex-direction column
  // justify-content center
  align-items center
  transition all .3s ease
  span
    position relative
    top -20px
    font-size 32px
    font-family Helvetica Neue For Number,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif
    color #333
.v-enter-from, .v-leave-to {
  opacity: 0;
}
.v-leave-from, .v-enter-to {
  opacity: 1;
}
</style>

<style type="text/css">
@keyframes ldio-c6v5n6da6eo {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.loadingio-spinner-spin-txhf5g2i8fm {
  margin-top: 45%;
  transform: scale(.5);
}
.ldio-c6v5n6da6eo div > div {
  position: absolute;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: #344bff;
  animation: ldio-c6v5n6da6eo 1s linear infinite;
}.ldio-c6v5n6da6eo div:nth-child(1) > div {
  left: 148px;
  top: 88px;
  animation-delay: -0.875s;
}
.ldio-c6v5n6da6eo > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 160px 100px;
}.ldio-c6v5n6da6eo div:nth-child(2) > div {
  left: 130px;
  top: 130px;
  animation-delay: -0.75s;
}
.ldio-c6v5n6da6eo > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 142px 142px;
}.ldio-c6v5n6da6eo div:nth-child(3) > div {
  left: 88px;
  top: 148px;
  animation-delay: -0.625s;
}
.ldio-c6v5n6da6eo > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 100px 160px;
}.ldio-c6v5n6da6eo div:nth-child(4) > div {
  left: 46px;
  top: 130px;
  animation-delay: -0.5s;
}
.ldio-c6v5n6da6eo > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 58px 142px;
}.ldio-c6v5n6da6eo div:nth-child(5) > div {
  left: 28px;
  top: 88px;
  animation-delay: -0.375s;
}
.ldio-c6v5n6da6eo > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 40px 100px;
}.ldio-c6v5n6da6eo div:nth-child(6) > div {
  left: 46px;
  top: 46px;
  animation-delay: -0.25s;
}
.ldio-c6v5n6da6eo > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 58px 58px;
}.ldio-c6v5n6da6eo div:nth-child(7) > div {
  left: 88px;
  top: 28px;
  animation-delay: -0.125s;
}
.ldio-c6v5n6da6eo > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 100px 40px;
}.ldio-c6v5n6da6eo div:nth-child(8) > div {
  left: 130px;
  top: 46px;
  animation-delay: 0s;
}
.ldio-c6v5n6da6eo > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 142px 58px;
}
.loadingio-spinner-spin-txhf5g2i8fm {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-c6v5n6da6eo {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-c6v5n6da6eo div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
